### ISSUE TITLE
Feature request: Add tinydb support

### ISSUE THREAD

**Issue by gmerrall** [requests-cache/requests-cache#103]
This might be a useful replacement for SQLite.  See https://github.com/msiemens/tinydb for more information,

**Comment by JWCook** [comment]
@gmerrall I see this issue is a couple years old now, but is this a feature you're still interested in? And since I haven't used tinydb myself, can you fill me in on what its advantages are over SQLite?

If you or someone else wants to submit a PR for this, I'd be happy to review it and get it merged in. But it would need to be added as a new backend, not a replacement for the existing SQLite backend.

**Comment by JWCook** [comment]
I am going to close this for now, as it's unlikely anyone else is going to implement this anytime soon. I'll still be happy to review a PR for this, and reopen this issue if anyone wants to discuss it more.
