### ISSUE TITLE
filesize limit for cache?

### ISSUE THREAD

**Issue by Almenon** [requests-cache/requests-cache#115]
Is there a way to configure a filesize limit for the cache? I see expire after but nothing for size. Such a feature would be nice to have.

Thanks for making the library, it's pretty simple to use :)

**Comment by JWCook** [comment]
That would be a bit difficult to do generically, since it would need to be implemented separately for each backend. What would you want the behavior to be once the filesize limit is reached? Raise an exception, start deleting cached responses, stop caching new responses, or other?

And is this something you'd like to submit a PR for?

**Comment by Almenon** [comment]
I think deleting old responses would be best approach.  I'm no longer using
request cache (I forget what I used it for initially tbh) so I'm not
interested in making a PR at the moment, sorry.

**Comment by JWCook** [comment]
Alright, I'm going to close this issue for now, then, but if anyone else wants this feature, feel free to comment and I'll reopen.

**Comment by JWCook** [comment]
For reference, this would fall under the category of alternative cache eviction methods; also see #116  and #364.
