### ISSUE TITLE
Feature proposition: cache redacted content

### ISSUE THREAD

**Issue by rom1sqr** [requests-cache/requests-cache#668]
Hi everyone!

I'd like to know what you guys think about the following addition to the features provided by this module.

Currently, as far as i understand, there is no way to redact a request in the cache.
Like, let's suppose i need to keep track if a request is using authentication, but i want the related headers to be free of any secret.
At the moment, the closest implemented feature is done via the `ignored_parameters`.
And it only allows me to either keep the whole `Authorization` header into the cached request, OR to remove it completely.
It seems i can't apply a function (or without loss of generality a callable) on the value of the header itself.

Moreover, there is another problem. For the module to be able to discriminate the cases where
i used authentication or not, i need to keep track of the redacted header in the cache key computation.
Unless i'm using a custom `key_fn` (which is a bit overkill i think), i can't do it easily.
The `match_headers` parameter allows me to either take a header into the key computation, or to remove
it completely, nothing in between.

I've actually modified a local version of this module, to allow the `match_headers` and `ignored_parameters`
to accept a dictionary value (which is fortunately a kind of iterable).

```diff
diff --git a/requests_cache/cache_keys.py b/requests_cache/cache_keys.py
index c2f295a..e074320 100644
--- a/requests_cache/cache_keys.py
+++ b/requests_cache/cache_keys.py
@@ -86,15 +86,20 @@ def get_matched_headers(
     """Get only the headers we should match against as a list of ``k=v`` strings, given an optional
     include list.
     """
-    if not match_headers:
-        return []
-    if match_headers is True:
-        match_headers = headers
-    return [
-        f'{k.lower()}={headers[k]}'
-        for k in sorted(match_headers, key=lambda x: x.lower())
-        if k in headers
-    ]
+    if   isinstance(match_headers, bool):
+         match_headers = { header: match_headers for header in headers }
+    elif isinstance(match_headers, (list, tuple)):
+         match_headers = { header: True for header in match_headers }
+    result = []
+    for header_name in sorted(match_headers, key=str.lower):
+        if  header_name not in headers:
+            continue
+        if  isinstance(match_headers[header_name], bool):
+            if  match_headers[header_name] == True:
+                result.append(f'{header_name.lower()}={headers[header_name]}')
+        elif callable(match_headers[header_name]):
+            result.append(f'{header_name.lower()}={match_headers[header_name](headers[header_name])}')
+    return result


 def normalize_request(
@@ -216,9 +221,18 @@ def filter_sort_json(data: Union[List, Mapping], ignored_parameters: ParamList):


 def filter_sort_dict(data: Mapping[str, str], ignored_parameters: ParamList) -> Dict[str, str]:
-    if not ignored_parameters:
-        return dict(sorted(data.items()))
-    return {k: v for k, v in sorted(data.items()) if k not in set(ignored_parameters)}
+    if  ignored_parameters is None:
+        ignored_parameters = {}
+    elif isinstance(ignored_parameters, (list, tuple)):
+        ignored_parameters = {k: True for k in ignored_parameters}
+    result = {}
+    for k, v in sorted(data.items()):
+        if  k in ignored_parameters and ignored_parameters[k] == True:
+            continue
+        if  k in ignored_parameters:
+            v = ignored_parameters[k](v)
+        result |= {k: v}
+    return result


 def filter_sort_list(data: List, ignored_parameters: ParamList) -> List:
```

It works like this:

- if you use a boolean value, the current behaviour is unchanged (`True` means match everything, `False` means remove everything)
- if you use a tuple or a list, then you keep the headers whose names are into this tuple or list (case insensitive match)
- if you use a dictionary (this is my new implementation), then:
  - if the value is a boolean, `True` means match the key, `False` means remove it
  - if the value is a callable, then match the result of the callable applied to the header value

For example:

```python
match_headers = { 'Authorization': lambda header: header.split(' ')[0] + ' ' + '**redacted**' }
```

would allow me to take into account the `Authorization` header into the key computation.
One entry in the cache for an unauthenticated request, and one for any authenticated request.

Same applies for the cache entry content:

```python
ignored_parameters = { 'Authorization': lambda header: header.split(' ')[0] + ' ' + '**redacted**' }
```

would allow me to redact the `Authorization` header into the cache entry.

I think this could be really useful, but the thing is: i think my current implementation is kinda ugly.

I actually hijacked the initial purpose of both of those parameters to suit my needs.
But i'm pretty convinced it would be cleaner to add another one to do that.
It could be `redacted_mapping` or something.

What do you guys think?

- Do you think this could be a useful feature added to this module?
- Do you want me to implement it?
- What's the best way to do it?
  - Using the already existing two parameters?
  - Or using a completely different one?
  - Merging all of them into a single one?

Any comment or question would be appeciated.

Thanks

**Comment by JWCook** [comment]
Hi, and thanks for the details! What you want to do makes sense, but I'm not sure this case is common enough to add a new feature to the library for it. Generally this is what a custom cache key function (`key_fn`) is for. Making a local patch like your example is very likely to break with future releases, since that module changes frequently.

If enough other users would find this useful, though, I would consider adding a it. Do you just need to match whether a param/header is present or not? I would prefer to avoid adding more callbacks to handle. The simplest option may be to add a separate Boolean parameter that changes the behavior of `ignored_parameters`.

I'm not sure exactly what to call that, but something like:
```python
session = CachedSession(
    ignored_parameters=['Authorization'],
    match_ignored_parameters_exist=True,  # Param name TBD
)
```

Also, an alternative workaround would be to not use `ignored_parameters` at all, and modify the cached content after the request, using [`BaseCache.save_response()`](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.base.html#requests_cache.backends.base.BaseCache.save_response). I could put together an example for that later.

**Comment by rom1sqr** [comment]
You're absolutely right :)

- the `match_ignored_parameters_exist` is indeed a very straightforward solution. but i thought it was not extensible enough.

Let's say i'm trying to cache requests i'm sending to an API. Imagine i'm POSTing content, let's say a picture on an image board, and the endpoint returns me the `picture_id` as json content. Maybe that would be useful to not store the actual value of the parameter (whether it be a response header, or a content field), but its existence and type.

Maybe that would be interesting to replace/redact:

```
{
  "_content": "{ 'picture_id': 932784 }"
}
```

by/with

```
{
  "_content": "{ 'picture_id': '**endpoint-generated integer**' }"
}
```

As you can see, it could be way deeper than just mentioning the simple existence of the value.
Being able to redact it could allow way more use cases.

- the idea of overloading BaseCache.save_response() is great! but i think we shouldn't have to :)

```python
    def save_response(self, response: AnyResponse, cache_key: str = None, expires: datetime = None):
        cache_key = cache_key or self.create_key(response.request)
        cached_response = CachedResponse.from_response(response, expires=expires)
        cached_response = redact_response(cached_response, self.ignored_parameters)  # <-------
        self.responses[cache_key] = cached_response
        for r in response.history:
            self.redirects[self.create_key(r.request)] = cache_key
```

as you can see, there is already a `redact_response()` call supposed to... redact the parameters.

Maybe `redact_response` could be overloaded with a param in `BaseCache.save_response()`?
The same way `key_fn` is working at the moment.

Anyway. I completely understand your point of view. I'm only bringing discussion / brainstorming. :)

**Comment by JWCook** [comment]
Thanks for the input. It's good to see examples like this to understand how people are using the library.

I will think on this a bit more, and get back to you.

**Comment by JWCook** [comment]
After thinking about this some more, I would be willing to make matching whether a param/header exists the default behavior for `ignored_parameters`. I think the downsides are minimal (an occasional cache miss in certain cases). And since common auth headers will be ignored by default in 1.0, I think this could lead to unexpected behavior in cases similar to yours (a single API endpoint working both with and without auth).

As for supporting callbacks for `ignored_parameters`, it's a cool idea, but I really think this is the kind of thing that a custom request matcher (`key_fn`) is better suited for, and seems too niche to add to the library directly.

If you still want to do that, here's an example that doesn't require patching the library or overriding any class methods:

```python
from requests_cache import CachedSession, create_key

def custom_create_key(request, ignored_parameters=None, redact_param_callback=None, **kwargs):
    """Optionally accept a callback to apply to ignored_parameters instead of fully ignoring them"""
    if redact_param_callback:
        request = request.copy()
        for k in ignored_parameters:
            if k in request.params:
                request.params[k] = redact_param_callback(request.params[k])
            if k in request.headers:
                request.headers[k] = redact_param_callback(request.params[k])
    return create_key(request, ignored_parameters=None, **kwargs)

session = CachedSession(key_fn=custom_create_key)
```

Or you could change that to accept `ignored_parameters` as a `{str: Callable}` dict like your original example. In general, the simplest way to make a custom request matcher is to let the default `create_key()` do most of the work, and either **modify the request before calling it**, or **modify the base cache key after calling it.**

I'm still glad you brought this up, though. Later on I may make some changes that would make a custom request matcher easier to write, for cases where the above approach just can't work (as in there's no way to reuse the default `create_key()` to do most of the work).
