### ISSUE TITLE
Package requirements on PyPI out of sync with Conda-Forge (attrs, cattrs, and exceptiongroup)

### ISSUE THREAD

**Issue by cheginit** [requests-cache/requests-cache#675]
This is the same `attrs` version issue that I opened for [aiohttp-client-cache](https://github.com/requests-cache/aiohttp-client-cache/issues/131).

You can check the log of my other package that failed due to this [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=544489&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d).

At the bottom, the log reads:

```
requests-cache 0.9.4 has requirement attrs<22.0,>=21.2, but you have attrs 22.1.0.
```

**Comment by JWCook** [comment]
This one is a bit trickier due to some issues with upstream dependencies on conda-forge (namely [cattrs and exceptiongroup](https://github.com/conda-forge/cattrs-feedstock/pull/19)). I'll see what I can do. One way or another, the conda dependencies will need to be slightly different than the pypi dependencies, at least for awhile.

Meanwhile, you can either add those version restrictions to your own `meta.yml`, or remove `pip check` (which is checking against pypi dependencies, not conda dependencies).

**Comment by JWCook** [comment]
requests-cache v0.9.5 is now on conda-forge. The `attrs` requirement now matches what's on PyPI, but `cattrs` and `exceptiongroup` do not, so `pip check` will still complain about this.

**Comment by cheginit** [comment]
Great! The latest conda version of my package already has `attrs<22.0` in its `mtal.yml` and it passed. So, I'll wait for the 0.9.6 version to pass and then will update mine accordingly.

Again, thanks for the quick fix!

**Comment by tjni** [comment]
Hi @JWCook,

I've been reading this and some of the linked issues. I want to fix this package in [nixpkgs](https://github.com/NixOS/nixpkgs), which packages only the latest versions of `attrs` and `cattrs` together.

I can patch `pyproject.toml` to unconstrain both `attrs` and `cattrs` locally in nixpkgs, but I want to double check with you that there is no known functional reason why one or the other needs to be constrained.

**Comment by JWCook** [comment]
> but I want to double check with you that there is no known functional reason why one or the other needs to be constrained.

Correct, there is currently no functional reason there needs to be an upper constraint on either of those.

I have had a few unexpected things break in this library after dependency updates, so I thought it would be useful to add upper constaints to some of them. I'm realizing this might cause more problems than it solves for downstream projects, though, so now I'm leaning toward dropping all upper constraints for non-dev dependencies, especially after reading [this article](https://iscinumpy.dev/post/bound-version-constraints/).

Any thoughts on that?

**Comment by tjni** [comment]
I've currently read about a quarter of that article. It's well-written in my opinion, and I look forward to reading more.

My personal opinion is that version constraints should be a way of communicating information. I usually don't know whether a future version of a package will break my code, so I stay silent. I tend to err on the side of fewer constraints, more freedom.

Version constraints can also be used to exercise control, e.g:

- I want to control how my library is used to only the versions or version ranges I have tested or I have blessed.
- I want to control how much maintenance I have to do, so I increase the lower version bound.
- I want to control how much blame I receive when my package breaks due to a dependency.
- etc.

All are valid needs, and each person is unique. Whatever you choose, I always encourage to first be compassionate to yourself, and choose something which makes you feel better about the state of affairs.

**Comment by JWCook** [comment]
Done! v0.9.6 is now out on both PyPI and Conda-Forge, and the version constraints are consistent again.

**Comment by cheginit** [comment]
Great. Thank you!

**Comment by glensc** [comment]
@JWCook ok, thanks for the info. the post is long but I try to read it.

ps: In the project I'm using request-cache, dependencies are pinned anyway:
- https://github.com/Taxel/PlexTraktSync/pull/1024/files
