### ISSUE TITLE
datetime.utcnow() is not offset-aware and should be replaced with datetime.now(timezone.utc)

### ISSUE THREAD

**Issue by sebastianrasor** [requests-cache/requests-cache#688]
### The problem
For some reason `datetime.utcnow()` is not offset-aware. This can be verified with `datetime.utcnow().tzinfo is None`.

`datetime.utcnow()` should be replaced with `datetime.now(timezone.utc)`, which is offset-aware. This can be verified with `datetime.now(timezone.utc).tzinfo is None`.

**Comment by JWCook** [comment]
Are you referring to `CachedResponse.created_at` and `expires`? Those are only created, modified, and compared internally, so they do not need to be timezone-aware. Any user- or header-provided datetimes are also [converted to timezone-naive UTC](https://github.com/requests-cache/requests-cache/blob/09de36a70e966925ed7a86652a3fbea704cf293b/requests_cache/policy/expiration.py#L76-L83). This is needed because not all storage backends have a native method to store a timezone offset.

Is there a specific problem you've encountered with this?
