### ISSUE TITLE
Pylance warning about reset_expiration expire_after parameter

### ISSUE THREAD

**Issue by masavini** [requests-cache/requests-cache#741]
hi,
i'm using this simple code in my application:
```python
if isinstance(_resp, CachedResponse):
    _resp.reset_expiration(expire_after=0)
```
pylance reports this:
```
Argument of type "Literal[0]" cannot be assigned to parameter "expire_after" of type "Module("requests_cache.models.response.ExpirationTime")" in function "reset_expiration"
  Type "Literal[0]" cannot be assigned to type "Module("requests_cache.models.response.ExpirationTime")"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```
is this expected?

**Comment by JWCook** [comment]
I'm able to reproduce this with VSCode and Pylance v2022.12.20. There aren't any `Literal` types defined in requests-cache, and it's bizarre that Pylance is calling `0` a `Literal[0]` instead of an int.

The type for that `expire_after` argument is defined like this:
```python
ExpirationTime = Union[None, int, float, str, datetime, timedelta]
```

Type checks pass with mypy, and I'm leaning toward saying this is a false positive with Pylance.

**Comment by JWCook** [comment]
After a bit of fiddling around, I was able to get Pylance to correctly recognize the `ExpirationTime` type. Until that change is released, you will need to add a `# type: ignore` there.

Thanks for reporting that, and let me know if you see any other type warnings with requests-cache.
