### ISSUE TITLE
Why save the same request twice?

### ISSUE THREAD

**Issue by Mosony** [requests-cache/requests-cache#748]
**It works with another API to overwrite the same request in the cache, but with this API it is saved twice.**

```
from requests_cache import CachedSession
import requests

session = CachedSession('fmc_cache', backend='sqlite', ignored_parameters=['X-auth-access-token'])

FMC_HEADERS = {'X-auth-access-token': 'TOKEN'}
url = 'https://HOST/api/fmc_config/v1/domain/DOMAIN_UUID/devices/devicerecords'

response = session.get(url, headers=FMC_HEADERS, verify=False)

with session.cache_disabled():
    response = session.get(url, headers=FMC_HEADERS, verify=False)
    session.cache.save_response(response)
    
print(session.cache.response_count())
for response in session.cache.values():
    print(response)
```

**UPDATE:**
When I use the verify parameter it is saved twice in the cache.
Do you have any idea why?
Thank you!

**Comment by JWCook** [comment]
Requests with and without `verify` are cached separately, because the server may return a different response if SSL cert verification is disabled (#70, #209). When you call `save_response()`, it's going to use a different cache key because `verify` happens to be the only piece of relevant request info that isn't saved on the response object, and it defaults to True. 

I realize that behavior isn't obvious, but here is a workaround you can use:
```
from requests_cache import CachedSession, create_key

session = CachedSession('fmc_cache', backend='sqlite', ignored_parameters=['X-auth-access-token'])
response = session.get(url, headers=FMC_HEADERS, verify=False)

cache_key = create_key(response.request, verify=False)
session.cache.save_response(response, cache_key)
```
