### ISSUE TITLE
1.0.0b0: stale_if_error and allowable_codes not working

### ISSUE THREAD

**Issue by DavidSchmidt00** [requests-cache/requests-cache#761]
### The problem
My settings: `requests_cache.CachedSession('my_cache', stale_if_error=True, expire_after=10, allowable_codes=[200, 404])`

The API-call i want to cache returns an error-code 500, and i have `stale_if_error` turned on. Previously the API returned a valid response (with payload and HTTP code 200), so the valid response is in the cache, but already expired.
I expect the session.get() call to returned the expired but valid reponse from the cache, because `stale_if_error` is turned on, but it returns the failed (500) response.

In addition to that, when the API returns 404, i expect the library to store the response, because its an allowable code.
But in this scenario the 404 response isn't stored and is just returned from the library call.

### Expected behavior

* Return the expired reponse and not store the failed response.
* Store failed responses, if they are in `allowable_codes`

### Steps to reproduce the behavior
```
session = requests_cache.CachedSession('my_cache', stale_if_error=True, expire_after=10, allowable_codes=[200, 404])

response = session.get(f"{URL}")  # API returns 500
```

### Workarounds
No

### Environment
- requests-cache version: 1.0.0b0
- Python version: 3.11.0
- Platform: Windows

**Comment by DavidSchmidt00** [comment]
I discovered an unexpected behavior in 0.9.7 as well and prepared a fix, but then discorverd the logic completely changed with 1.0.0b0.
If you can reproduce the bug, i would love to provide a fix in 1.0.0 as well :)

**Comment by JWCook** [comment]
I'll look into it. Thank you for the details!

**Comment by JWCook** [comment]
There may be something else specific to your request that's causing this, since I'm not able to reproduce this in either 0.9.7 or main. 


### Example unit test
There are already some tests to cover relevant cases for `allowable_codes` and `stale_if_error`, but here's one closer to your example. This uses `requests_mock` (plus some helper functions [here](https://github.com/requests-cache/requests-cache/blob/main/tests/conftest.py)) to simulate a request that returns a 404 and then a 500:

```python
def test_stale_if_error__allowable_codes(mock_session: CachedSession):
    mock_session.settings.stale_if_error = True
    mock_session.settings.expire_after = 10
    mock_session.settings.allowable_codes = (200, 404)

    # Add an expired 404 response to the cache, and copy to a cache key that will match 500 response
    response_404 = mock_session.get(MOCKED_URL_404)
    response_500 = CachedResponse.from_response(mock_session.get(MOCKED_URL_500))
    mock_session.cache.save_response(
        response_404,
        cache_key=mock_session.cache.create_key(response_500.request),
        expires=datetime.utcnow() - timedelta(seconds=1),
    )

    # Make sure the 404 was cached
    assert mock_session.get(MOCKED_URL_404).from_cache is True

    # A subsequent request that returns a 500 should return the stale cached 404 response
    response = mock_session.get(MOCKED_URL_500)
    assert response.from_cache is True and response.is_expired is True
    assert response.status_code == 404
```

### Troubleshooting steps

Could you reproduce this again, but [turn on debug logs](https://requests-cache.readthedocs.io/en/stable/user_guide/troubleshooting.html#logging) and show me the output? Or come up with a reproducible example using `requests-mock` or a similar tool?

Some other things to check:
* Was the prior 404 response cached with a different version of requests-cache? In that case, the cache key may be different for the new request, meaning the cache won't be able to find your previously cached 404 response.
* Is there any possibility of request headers, body, or other details changing between the successful request (404) and the failed one (500)?
* Manually inspect the cache to confirm whether or not the 404 response was cached.
  * Example:
    ````python
    for key, response in session.cache.responses.items():
        if response.status_code == 404:
            print(key, response)
    ````
  * More info and examples here: https://requests-cache.readthedocs.io/en/main/user_guide/inspection.html

**Comment by JWCook** [comment]
Hi @DavidSchmidt00, have you been able to reproduce this again with debug logs?

**Comment by DavidSchmidt00** [comment]
Hi, sorry for the delay. I just built a new simple test-app and it behaves the same.
I'll try to build some tests to reproduce the behavior later today or tomorrow.

**Comment by DavidSchmidt00** [comment]
Hi @JWCook,
in https://github.com/DavidSchmidt00/requests-cache-bug-test i built a test-case which demonstrate the (imo) faulty behavior.



For requests-cache 0.9.7 this can be fixed by adding a `if response.status_code not in self.allowable_codes:` before the `response.raise_for_status()` in https://github.com/requests-cache/requests-cache/blob/v0.9/requests_cache/session.py#L231

**Comment by JWCook** [comment]
Ah, thanks, that's very helpful! I think my test above was incorrect. Since you already wrote a test and found the fix, would you like to submit a PR for that?

If so, don't worry about the `0.9` branch for now; I likely won't make another patch release for that since I plan to release 1.0 in about a month.
