### ISSUE TITLE
Randomize expire

### ISSUE THREAD

**Issue by glensc** [requests-cache/requests-cache#768]
I have some requests whose reponses change not very often, so long expiry makes sense. but not to hit the cache all the same time would be nice to randomize the expire, say something between 3w to 4w. 

I'm currently using urls_expire_after patterns.

some idea is to use tuple for the pattern value and request-cache would do randomization:

```py
urls_expire_after = {
    '*.site_1.com': 30,
    'site_2.com/resource_1': (60 * 2, 60 * 4),
    'site_2.com/resource_2': (timedelta(weeks=4 * 3), timedelta(weeks=4 * 4))
    'site_2.com/static': -1,
}
session = CachedSession(urls_expire_after=urls_expire_after)
```

**Comment by JWCook** [comment]
If I understand correctly, the main thing you want to avoid is refreshing several cached requests at the same time? I think that makes sense, but let's think through some other options before considering random expiration.

Are these requests sent immediately one after another, like this?
```python
response_1 = session.get(url_1)
response_2 = session.get(url_2)
...
response_n = session.get(url_n)
```
If so, they could be sent in parallel from different threads.

Otherwise, the [stale_while_revalidate](https://requests-cache.readthedocs.io/en/main/user_guide/expiration.html#asynchronous-revalidation) option would accomplish close to the same thing. I made a small compromise there that I think would be useful in your case: instead of strictly following same behavior as the `Cache-Control: stale-while-revalidate` header ([RFC 5861](https://datatracker.ietf.org/doc/html/rfc5861#section-3)), I made the `stale_while_revalidate` keyword argument apply to _all_ refresh requests, not just revalidation requests.

That means that if all those requests expire and are re-requested at the same time, `CachedSession` will first return the expired cached responses, then send requests to update the cache from a separate thread, so your main thread doesn't have to wait for the responses.

That's still only in the beta, and I'm not 100% sure yet if that's the best way to handle it. I was considering splitting that into two separate arguments like `stale_while_revalidate` and `stale_while_refresh`, since there are slightly different use cases for each, but I don't know if anyone actually needs that currently. Any thoughts on that?

**Comment by JWCook** [comment]
I'll close this for now, but let me know if either of the options above work for you, or if you have any other thoughts on this.
