### ISSUE TITLE
stale_if_error=True doesn't seem to work in case there's no Internet connection

### ISSUE THREAD

**Issue by pfalcon** [requests-cache/requests-cache#889]
### The problem
For me, primary use of `stale_if_error=True` would be: in case I have cached responses, and currently I'm offline, then I can still use those cached responses. However, that doesn't seem to work.

The code:
```
session = requests_cache.CachedSession(
    '.api_cache',
    backend='filesystem',
    expire_after=1800,
    stale_if_error=True,
)
requests_cache.install_cache(session)
```

With Internet connection down for testing, I get:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:
[...]
  File "/home/pfalcon/.local/lib/python3.10/site-packages/requests_cache/session.py", line 158, in request
    return super().request(method, url, *args, headers=headers, **kwargs)  # type: ignore
  File "/home/pfalcon/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pfalcon/.local/lib/python3.10/site-packages/requests_cache/session.py", line 205, in send
    response = self._send_and_cache(request, actions, cached_response, **kwargs)
  File "/home/pfalcon/.local/lib/python3.10/site-packages/requests_cache/session.py", line 229, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/home/pfalcon/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/pfalcon/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='...', port=443): Max retries exceeded with url: /... (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc453b91ae0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

### Expected behavior
See above.

### Steps to reproduce the behavior
See above.

### Workarounds
No workarounds, this blocks important expected usage of the cache.

### Environment
- requests-cache version: 1.1.0
- Python version: 3.10
- Platform: Ubuntu 22.04

**Comment by JWCook** [comment]
`install_cache()` doesn't accept a session object. The first arg is `cache_name`, so if you pass an object to that, the object's string representation will be used as the cache name... which for the SQLite and Filesystem backends, will be used as a filename. That's the first time I've seen that, though!

Side note: `install_cache()` does accept a `session_factory` argument, which can be a session **class or callable** that returns a session object. The reason you can pass a class/factory but not an object is because `requests` will create a new implicit session object for each request when you use the simplified/stateless API (`requests.get`, `requests.post`, etc.).

I believe your example will do what you expect if you pass those arguments to `install_cache()` directly.

And if you want fully offline usage, you can use the `only_if_cached` option: https://requests-cache.readthedocs.io/en/stable/user_guide/expiration.html#cache-only-requests

**Comment by pfalcon** [comment]
An example of a few layers of user confusion, as elaborated in https://github.com/requests-cache/requests-cache/issues/890#issuecomment-1760184409.

Thanks for patient response, confirming works as expected when done right, per above link.

**Comment by JWCook** [comment]
Good! Feel free to open another issue (or PR) if you have more suggestions for documentation that could be clearer for new users.
