### ISSUE TITLE
Feature request: add database permissions check

### ISSUE THREAD

**Issue by woodholly** [requests-cache/requests-cache#894]
When database file is readonly or python can't write into database file, or can't write to directory containing database **crazy!**", it leads to "sqlite3.OperationalError: no such column: expires" which is misleading.

**Comment by JWCook** [comment]
If the file already exists and you have read but not write permissions, you will get (on session init):
```py
OperationalError: attempt to write a readonly database
```

If the file already exists and you don't have read permissions, you will get:
```py
OperationalError: unable to open database file
```

And if you don't have permissions to the parent directory, you will get:
```py
OperationalError: unable to open database file
```

So I will need more info to help you out. Please fill out the [bug report template](https://github.com/requests-cache/requests-cache/issues/new?assignees=&labels=bug&projects=&template=bug.md&title=) with a complete code example that reproduces the problem. You can update this issue instead of creating a new one, if you prefer.
