### ISSUE TITLE
Failing to initialize backend with pymongo >= 4.0

### ISSUE THREAD

**Issue by rcarausu** [requests-cache/requests-cache#914]
pymongo dropped boolean evaluation for database objects in version 4.0.

See [migration guide from 3 o 4](https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#database-bool-raises-notimplementederror) and [related github commit](https://github.com/mongodb/mongo-python-driver/compare/3.12.0...4.0#diff-fea5af5b145e4376d3484eb5d647c0fd219bad8f07af1bae72de75ae3c1eba08R828).

This raises a RuntimeError when using requests-cache with MongoDB as a backend and pymongo>=4.0.

```
    self.session = CachedSession(backend='mongodb', connection=mongo_client, cache_control=True, expire_after=timedelta(days=TTL_IN_DAYS))
  File "/usr/local/lib/python3.7/site-packages/requests_cache/session.py", line 61, in __init__
    self.cache = init_backend(cache_name, backend, serializer=serializer, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_cache/backends/__init__.py", line 91, in init_backend
    return BACKEND_CLASSES[backend](cache_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_cache/backends/mongodb.py", line 47, in __init__
    **skwargs,
  File "/usr/local/lib/python3.7/site-packages/requests_cache/backends/mongodb.py", line 92, in __init__
    self.connection = connection or MongoClient(**connection_kwargs)
  File "/usr/local/lib/python3.7/site-packages/pymongo/database.py", line 1338, in __bool__
    "Database objects do not implement truth "
NotImplementedError: Database objects do not implement truth value testing or bool(). Please compare with None instead: database is not None
```

### Expected behavior
It should properly initialize the cache with a MongoDB backend.

### Steps to reproduce the behavior
Both with `CacheSession()` and with `requests_cache.install_cache()` calls.

### Workarounds
Not that I've found of.

I think [line 92 from requests_cache/backends/mongodb.py](https://github.com/requests-cache/requests-cache/blob/c889279f6e9e5e0fdaf56f6449da08ef4d2e5576/requests_cache/backends/mongodb.py#L92C26-L92C26) should be changed to:
```python
self.connection = connection if connection is not None else MongoClient(**connection_kwargs)
```

This seems to fix it.

### Environment
- requests-cache version: `any`
- pymongo version: `>=4.0`
- Python version: `>=3.7`
- Platform: Docker with `python:3.7` image

**Comment by JWCook** [comment]
`MongoClient`doesn't override `__bool__`, so this shouldn't be an issue with pymongo 4+. Example usage:
```py
from pymongo import MongoClient
from requests_cache import CachedSession, MongoCache

backend = MongoCache(connection=MongoClient(host='mongodb://0.0.0.0', port=27017))
session = CachedSession(backend=backend)
```

Or are you saying you want to pass a `pymongo.database.Database` object instead of `MongoClient`?

**Comment by rcarausu** [comment]
You are right, I was trying to use the Database object instead of MongoClient. Sorry for wasting your time 😓

Thanks for answering! I'm going to close it.

**Comment by JWCook** [comment]
This would have kind of worked on accident, since pymongo lets you chain getattr/getitem calls on `Database`, `MongoClient`, and `Connection`. For example, `client.db.collection.sub_collection` or  `client['db']['collection']['sub_collection']`.

By default, requests-cache will create a database named `http_cache` (which you can change with the [`db_name`](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.backends.mongodb.html#requests_cache.backends.mongodb.MongoCache) parameter), with a main collection named `responses`. If you happened to pass a `Database` object instead of `MongoClient`, you'd end up with a nested collection with the full namespace of `<my_db>.http_cache.responses`. That works just fine, it's just not a case that I expected or tested for.

I would be fine with making the change you suggested so your old piece of code still works, although it's still possible it might break again in the future. And feel free to open a new issue if you run into any other problems. If nothing else, it helps others who might be searching for the same thing.
