### ISSUE TITLE
Remove all requests to a particular URL

### ISSUE THREAD

**Issue by nschloe** [requests-cache/requests-cache#935]
When doing a request to `https://example.com/a`, I know it implicitly invalidates all requests to the URL `https://example.com/b`. I would hence like to remove all those requests from the cache. Apparently

```python
cached_session.cache.delete(
    urls=[
        f"https://example.com/b",
    ]
)
```

only removes `GET` requests, and requests with a payload are also not removed. I can check this with

```python
cached_session.cache.contains(
    request=Request(
        "POST",
        f"https://example.com/b",
        json={"foo": some_data},
    )
)
```

which still says `True` after the above deletion.

It seems easy enough to supply this exact `Request` to the `delete` call, but I don't know `some_data` at the time of deletion. Ideally I'd like to have the `json` attribute ignored ("match any").

Any hints?

**Comment by JWCook** [comment]
Short answer:
```py
for r in session.cache.responses.values():
    if r.url == "https://example.com/b":
        session.cache.delete(r.cache_key)
```

Longer answer:

`CachedSession.cache.delete()` uses the full request matching logic to match exact cache keys, not individual request attributes. The default backend (SQLite) only stores the cache key and serialized response data (plus an index for deleting expired responses). Since the request body is included in the cache key, the only way to ignore it is to iterate over all the responses in the cache.

This is still reasonably fast for a small to medium sized cache, but isn't efficient for a very large cache.

**Comment by nschloe** [comment]
Thanks!
